---
- name: Ensure Docker is installed
  hosts: all
  remote_user: ec2-user
  gather_facts: true
  become: true
  tasks:
    - name: Install Docker
      yum: name=docker

    - name: Ensure docker service is started and enabled
      service:
        name: docker
        state: started
        enable: yes